using PandemicTDD.Materiel.BoardItems;

namespace PandemicTDD.Materiel.Initializers
{
    public class TownLinksInitializer
    {
        public string[][] links = new string[][]{
            new string[]{TownsInitializer.Mumbai, TownsInitializer.Chennai},
            new string[]{TownsInitializer.Mumbai, TownsInitializer.Karachi},
            new string[]{TownsInitializer.Mumbai, TownsInitializer.Delhi},
            new string[]{TownsInitializer.Chennai, TownsInitializer.Delhi},
            new string[]{TownsInitializer.Chennai, TownsInitializer.Calcutta},
            new string[]{TownsInitializer.Chennai, TownsInitializer.Bangkok},
            new string[]{TownsInitializer.Chennai, TownsInitializer.Jakarta},
            new string[]{TownsInitializer.Karachi, TownsInitializer.Téhéran},
            new string[]{TownsInitializer.Karachi, TownsInitializer.Bagdad},
            new string[]{TownsInitializer.Karachi, TownsInitializer.Riyad},
            new string[]{TownsInitializer.Karachi, TownsInitializer.Delhi},
            new string[]{TownsInitializer.Delhi, TownsInitializer.Calcutta},
            new string[]{TownsInitializer.Delhi, TownsInitializer.Téhéran},
            new string[]{TownsInitializer.Calcutta, TownsInitializer.Hong_Kong},
            new string[]{TownsInitializer.Calcutta, TownsInitializer.Bangkok},
            new string[]{TownsInitializer.Bangkok, TownsInitializer.Hong_Kong},
            new string[]{TownsInitializer.Bangkok, TownsInitializer.Ho_Chi_Minh_Ville},
            new string[]{TownsInitializer.Bangkok, TownsInitializer.Jakarta},
            new string[]{TownsInitializer.Jakarta, TownsInitializer.Ho_Chi_Minh_Ville},
            new string[]{TownsInitializer.Jakarta, TownsInitializer.Sydney},
            new string[]{TownsInitializer.Téhéran, TownsInitializer.Bagdad},
            new string[]{TownsInitializer.Téhéran, TownsInitializer.Moscou},
            new string[]{TownsInitializer.Bagdad, TownsInitializer.Istanbul},
            new string[]{TownsInitializer.Bagdad, TownsInitializer.Le_Caire},
            new string[]{TownsInitializer.Bagdad, TownsInitializer.Riyad},
            new string[]{TownsInitializer.Riyad, TownsInitializer.Le_Caire},
            new string[]{TownsInitializer.Hong_Kong, TownsInitializer.Shanghai},
            new string[]{TownsInitializer.Hong_Kong, TownsInitializer.Taipei},
            new string[]{TownsInitializer.Hong_Kong, TownsInitializer.Manille},
            new string[]{TownsInitializer.Hong_Kong, TownsInitializer.Ho_Chi_Minh_Ville},
            new string[]{TownsInitializer.Ho_Chi_Minh_Ville, TownsInitializer.Manille},
            new string[]{TownsInitializer.Sydney, TownsInitializer.Los_Angeles},
            new string[]{TownsInitializer.Sydney, TownsInitializer.Manille},
            new string[]{TownsInitializer.Moscou, TownsInitializer.Saint_Petersbourg },
            new string[]{TownsInitializer.Moscou, TownsInitializer.Istanbul},
            new string[]{TownsInitializer.Istanbul, TownsInitializer.Saint_Petersbourg},
            new string[]{TownsInitializer.Istanbul, TownsInitializer.Milan},
            new string[]{TownsInitializer.Istanbul, TownsInitializer.Alger},
            new string[]{TownsInitializer.Istanbul, TownsInitializer.Le_Caire},
            new string[]{TownsInitializer.Le_Caire, TownsInitializer.Alger},
            new string[]{TownsInitializer.Le_Caire, TownsInitializer.Khartoum},
            new string[]{TownsInitializer.Shanghai, TownsInitializer.Pékin},
            new string[]{TownsInitializer.Shanghai, TownsInitializer.Séoul},
            new string[]{TownsInitializer.Shanghai, TownsInitializer.Tokyo},
            new string[]{TownsInitializer.Shanghai, TownsInitializer.Taipei},
            new string[]{TownsInitializer.Taipei, TownsInitializer.Manille},
            new string[]{TownsInitializer.Taipei, TownsInitializer.Osaka},
            new string[]{TownsInitializer.Manille, TownsInitializer.Sydney},
            new string[]{TownsInitializer.Manille , TownsInitializer.San_Francisco},
            new string[]{TownsInitializer.Los_Angeles, TownsInitializer.San_Francisco},
            new string[]{TownsInitializer.Los_Angeles, TownsInitializer.Mexico},
            new string[]{TownsInitializer.Los_Angeles, TownsInitializer.Chicago},
            new string[]{TownsInitializer.Saint_Petersbourg, TownsInitializer.Essen},
            new string[]{TownsInitializer.Milan, TownsInitializer.Essen},
            new string[]{TownsInitializer.Milan, TownsInitializer.Paris},
            new string[]{TownsInitializer.Alger, TownsInitializer.Madrid},
            new string[]{TownsInitializer.Alger, TownsInitializer.Paris},
            new string[]{TownsInitializer.Khartoum, TownsInitializer.Lagos},
            new string[]{TownsInitializer.Khartoum, TownsInitializer.Kinshasa},
            new string[]{TownsInitializer.Khartoum, TownsInitializer.Johannesbourg},
            new string[]{TownsInitializer.Pékin, TownsInitializer.Séoul},
            new string[]{TownsInitializer.Séoul, TownsInitializer.Tokyo},
            new string[]{TownsInitializer.Tokyo, TownsInitializer.Osaka},
            new string[]{TownsInitializer.Tokyo, TownsInitializer.San_Francisco},
            new string[]{TownsInitializer.San_Francisco, TownsInitializer.Chicago},
            new string[]{TownsInitializer.Mexico, TownsInitializer.Miami},
            new string[]{TownsInitializer.Mexico, TownsInitializer.Bogota},
            new string[]{TownsInitializer.Mexico, TownsInitializer.Lima},
            new string[]{TownsInitializer.Mexico, TownsInitializer.Chicago},
            new string[]{TownsInitializer.Chicago, TownsInitializer.Montréal},
            new string[]{TownsInitializer.Chicago, TownsInitializer.Atlanta},
            new string[]{TownsInitializer.Essen, TownsInitializer.Londres},
            new string[]{TownsInitializer.Essen, TownsInitializer.Paris},
            new string[]{TownsInitializer.Paris, TownsInitializer.Londres},
            new string[]{TownsInitializer.Paris, TownsInitializer.Madrid},
            new string[]{TownsInitializer.Madrid, TownsInitializer.Londres},
            new string[]{TownsInitializer.Madrid, TownsInitializer.Sao_Paulo},
            new string[]{TownsInitializer.Madrid, TownsInitializer.New_York},
            new string[]{TownsInitializer.Lagos, TownsInitializer.Kinshasa},
            new string[]{TownsInitializer.Lagos, TownsInitializer.Sao_Paulo},
            new string[]{TownsInitializer.Kinshasa, TownsInitializer.Johannesbourg},
            new string[]{TownsInitializer.Montréal, TownsInitializer.New_York},
            new string[]{TownsInitializer.Montréal, TownsInitializer.Washington},
            new string[]{TownsInitializer.Atlanta, TownsInitializer.Washington},
            new string[]{TownsInitializer.Atlanta, TownsInitializer.Miami},
            new string[]{TownsInitializer.Londres, TownsInitializer.New_York},
            new string[]{TownsInitializer.Sao_Paulo, TownsInitializer.Buenos_Aires},
            new string[]{TownsInitializer.Sao_Paulo, TownsInitializer.Bogota},
            new string[]{TownsInitializer.New_York, TownsInitializer.Washington},
            new string[]{TownsInitializer.Miami, TownsInitializer.Bogota},
            new string[]{TownsInitializer.Bogota, TownsInitializer.Lima},
            new string[]{TownsInitializer.Bogota, TownsInitializer.Buenos_Aires},
            new string[]{TownsInitializer.Lima, TownsInitializer.Santiago},
        };

        public void InitTownsLinks(Board board)
        {
            foreach (string[] link in links)
            {
                TownsLink tlink = new(link[0], link[1]);
                board.Link2Towns(tlink);
            }
        }
    }
}
